version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        expose:
            - 10000

    webserver:
        image: nginx:alpine
        container_name: nginx_web
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
